### ISSUE TITLE
This app is damaged

### ISSUE THREAD

**Issue by alucardontop** [mackonsti/yet-another-nfo-viewer#6]
I needed to manually sign the app since the latest release says that the app is damaged.

**Comment by mackonsti** [comment]
This application is not signed, @alucardontop with some official certificate.
So you can code-sign it by yourself as you mention, in Terminal (I think I have it right... be careful there needs to be a dash character alone):
```
cd /Applications/
sudo codesign -f -s - Yet\ Another\ NFO\ Viewer.app
```
Despite having cleaned the application from extended attributes, try to clean them again in Terminal:
```
cd /Applications/
xattr -rc Yet\ Another\ NFO\ Viewer.app
```
Sorry that I can't help more. Closing the ticket.

**Comment by alucardontop** [comment]
You don't need a certificate to be able to open unsigned apps. You usually can just right-click and press open it to bypass the security measure. This app says it's damaged, which is a different thing. This is the message I get whenever an app isn't signed: 
![image](https://user-images.githubusercontent.com/89560393/176170513-c1ec1604-4b82-4dfc-a19d-63fbc30a7db7.png)
But the message I'm getting here is different, it's this: 
![image](https://user-images.githubusercontent.com/89560393/176170779-aa788820-50a0-42a8-a47f-d100f4e74b99.png)
Also, you don't need to codesign the app, I just tested it and all you need to do is clean the extended attributes.
Since most people don't know how to fix this problem, it might be a good idea to add a remedy to this problem in the readme.

**Comment by mackonsti** [comment]
Hi @alucardontop thanks for your message.

Your request in the first post, talked about "_needed to manually sign the app since the latest release says that the app is damaged._" so I tried replying to this.

The DMG shared is clean from any extended attributes, but it seems they are added back when copied on the Mac.

So again, I am sorry but I am not sure of the result; were you replying to yourself (and others)? Did you manage to open it by cleaning the extended attributes? Did you use the right-click "Open" popup menu option?

Which platform / OS are you using? I am currently on Catalina (Intel) and Monterey (M1) and it works as expected.

I will add in the main page README.md a note for cleaning extended attributes but, I thought that people needing to read NFO files, are more than basic users and know already of this MacOS particularity 😄

**Comment by alucardontop** [comment]
I was replying to you and clarifying my problem. I'm on macOS Ventura beta 2, this may be the reason. When macOS releases Ventura to the public, this might still be there though. 
Most people reading NFO files are people pirating media/software, so they might not ALL be knowledgeable about macOS :)
